text_to_speech/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("text_to_speech_app.urls"))
]

text_to_speech_app/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path("",views.home_page,name="home"),
    path("get_mp3/",views.get_mp3,name="get_speech")
]

text_to_speech_app/models.py
from django.db import models

# Create your models here.

text_to_speech_app/forms.py
from django import forms
TLD_CHOICES=(
    ('com.au','Australian'),
    ('co.za','South Africa',),
    ('co.uk','British'),
    ('co.in','Indian'),
    ('ca','Canadian'),
    ('ie','Irish'),
    ('es','Spanish')
)
class TextForm(forms.Form):
    tld = forms.ChoiceField(choices=TLD_CHOICES,label="Enter your accent",widget=forms.Select(attrs={'class':'form-control'}))
    text= forms.CharField(label="Enter your text",widget=forms.Textarea(attrs={'rows':6,'cols':65,'class':'p-2 mt-0 mb-1'}))

text_to_speech_app/views.py
from django.shortcuts import render
from .forms import TextForm
from django.http import JsonResponse
from django.contrib import messages
from Text_To_Speech_SRC.components.text_to_speech import TextToSpeechApplication
from Text_To_Speech_SRC.logger import logging
import json
from django.views.decorators.csrf import csrf_exempt
# Create your views here.


def home_page(request):
    logging.info(f"You are in Home page .")
    form=TextForm()
    return render(request,"text_to_speech_app/home.html",{"form":form})


@csrf_exempt
def get_mp3(request):
    data=json.loads(request.body)
    print(data)
    text=data['text']
    tld=data['tld']
    logging.info(f"data entered by user {text} and accent value {tld}")
    print(text,tld)
    audio_string=TextToSpeechApplication().get_text_to_speech(text=text,accent=tld)
    result=audio_string.decode('utf8')
    newdata={
        "mp3string":result,
    }
    return JsonResponse(json.dumps(newdata),content_type="application/json",safe=False)

text_to_speech_app/templates/text_to_speech_app/baselayout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Text to Speech</title>
    <link rel="stylesheet" href="{% static 'text_to_speech_app/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'text_to_speech_app/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'text_to_speech_app/css/core.css' %}">
    <script src="{% static 'text_to_speech_app/js/jquery.js' %}"></script>
    <script src="https://kit.fontawesome.com/b8a169592b.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <div class="container-fluid">
        <h2 class="text-center projectheader pb-1">Text to Speech</h2>
        {% block content %}
        
        {% endblock content %}
    </div>
    <script src="{% static 'text_to_speech_app/js/jquery.js' %}"></script>
    <script src="{% static 'text_to_speech_app/js/bootstrap.min.js' %}"></script>

    {% block custom_js %}
    

    {% endblock custom_js %}



</body>
</html>

text_to_speech_app/templates/text_to_speech_app/home.html
{% extends "text_to_speech_app/baselayout.html" %}

{% block content %}
    <div class="container">
        
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow p-3 mt-3 text-center">
                    <form action="" method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            {{field.label_tag}} <br><span class="errors">{{field.errors|striptags}}</span>
                            {{field}} <br>
                        {% endfor %}
                        <input type="submit" value="Get speech" id="getspeech" class="btn form-control btn-dark">
                    </form>
                </div>
            </div>
            <div class="col-md-6">
                
                <div class="card shadow p-3 mt-3 ">
                    <p class="text-center fw-bold">Your speech in accent </p>
                    {% if messages %}           
                        {% for message in messages %}
                            <div class="text-center alert alert-primary alert-{{message.tags}} alert-dismissible fade show" role="alert">
                                {{message}}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}             
                    {% endif %}
                    <div class="text-center mt-5">
                        <audio id="audioid" controls >
                            <source  src="" type="audio/mpeg">
                        </audio>
                    </div>
                </div>
            </div>
        </div>
        <div id="myid">

        </div>
        
    </div>
    
{% endblock content %}


{% block custom_js %}

    <script>
        function base64ToBlob(base64, mime) 
        { 
            const byteChars = atob(base64); 
            const byteNumbers = new Array(byteChars.length); 
            for (let i = 0; i < byteChars.length; i++) 
            { 
                byteNumbers[i] = byteChars.charCodeAt(i); 
            } 
            const byteArray = new Uint8Array(byteNumbers); 
            return new Blob([byteArray], {type: mime}); 
        }

        document.querySelector("#getspeech").addEventListener("click",function(e){
            e.preventDefault();
            var tld=document.querySelector("#id_tld").value
            var text=document.querySelector("#id_text").value
            var data={
                "tld":tld,
                "text":text
            }
            console.log(data)
            var audio_id=document.getElementById("audioid")
            var accent = document.getElementById("id_tld")
            accent_value=accent.value
            fetch('{% url "get_speech" %}',{
                method:"POST",
                body:JSON.stringify(data),
                headers: {'Content-Type': 'application/json'}
            })
            .then(function(response){
                console.log(response)
                return response.json()
                               
            })
            .then(function(response){
                return JSON.parse(response)
            })
            .then(function(response){
                console.log("mp3 : ",response.mp3string)
                return base64ToBlob(response.mp3string, 'audio/mp3');
            })
            .then(function(blob){
                const audioUrl = URL.createObjectURL(blob);
                audio_id.src=audioUrl
                console.log(audioUrl)
            })
            .catch(error => {
                console.error('Fetch error:', error);
              });
        })
    </script>

{% endblock custom_js %}